### ISSUE TITLE
Snapper breaks when a lazy list has a large number of items

### ISSUE THREAD

**Issue by boswelja** [chrisbanes/snapper#13]
## Describe the bug
Trying to snap when item indexes are large numbers, snapper snaps back to the current item

## To Reproduce
Minimal reproducible sample:
```kotlin
@OptIn(ExperimentalSnapperApi::class)
@Composable
fun SnapperBug() {
    val modifier = Modifier
        .fillMaxWidth()
        .aspectRatio(1f)
    val lazyListState = rememberLazyListState(
        initialFirstVisibleItemIndex = Int.MAX_VALUE / 2
    )
    LazyRow(
        modifier = modifier,
        state = lazyListState,
        flingBehavior = rememberSnapperFlingBehavior(lazyListState)
    ) {
        items(
            count = Int.MAX_VALUE,
            key = { it }
        ) { index ->
            Box(modifier) {
                Text(
                    index.toString(),
                    modifier = Modifier.align(Alignment.Center)
                )
            }
        }
    }
}
```
Steps to reproduce:
1. Load the above Composable
2. Scroll once, note the first scroll is successful
3. Try to scroll again, note snapper now snaps back to the initial item immediately.

## Expected behavior
Snapper continues to snap across the entire range of items

## Screenshots?
I can attach a video if necessary

## Environment:
 - Android OS version: 12L (API32)
 - Device: Resizable Emulator
 - Library version: 0.1.2
 - Compose version: 1.2.0-alpha02 (Also reproducible with Compose 1.1.0-rc01)

## Additional context
If you significantly lower the initial page in the above sample, snapper starts to work normally

**Comment by chrisbanes** [comment]
I can't reproduce this using Compose 1.0.3, 1.1.0-rc01 or 1.2.0-alpha02. Can you attach a video?

**Comment by boswelja** [comment]
Sure thing, here you go

https://user-images.githubusercontent.com/15526339/152638604-9de4a252-487c-4a9d-ad6e-3493ead0209e.mp4

Interesting that you weren't able to replicate, were you running on an emulator too?

**Comment by chrisbanes** [comment]
Yep, just a standard API 31 Pixel emulator. I'll try on 12L but I'd be surprised if that is the cause.

**Comment by boswelja** [comment]
Ah I just noticed my snippet above had an initial value of 100, which works for me too
Have updated it to be half of Int.MAX_SIZE, which is the same value the above screenrecord used

**Comment by chrisbanes** [comment]
Ah thanks, I'll give it another try.

**Comment by chrisbanes** [comment]
Managed to get a test to repro this. Now to fix... 🤔
