### ISSUE TITLE
rememberSnapperFlingBehavior for scrollable Row

### ISSUE THREAD

**Issue by hrach** [chrisbanes/snapper#18]
We have horizontally scrollable container/content. It contains about 1 to 3 (at most) containers. The design requires to have the boxes the same height, so we use intrinsic height sizing (and of course, the width is also the same). Using intrinsic is forbidden in LazyRow, so we are currently using normal scrollable Row. 

![image](https://user-images.githubusercontent.com/284263/153773277-158f3951-04e5-45b5-a543-197e91db1e9d.png)

It could be probably done via custom SnapperLayoutInfo, yet it seems like enormous and non trivial work/amount of code.

Do you have any idea how to make it easier?

**Solution I'd like**
I am not much sure, maybe something like this?
```kotlin
val state = rememberScrollState()
val flingBehavior = rememberSnapperFlingBehavior(state, itemWidth = 200.dp)
Row(
    Modifier
        .horizontalScroll(
            state = state,
            flingBehavior = flingBehavior,
        )
)
```

**Alternatives I've considered**

- having custom snapping code (what we have now)
- implementing SnapperLayoutInfo

**Comment by chrisbanes** [comment]
`flingBehavior`s have no control over the layout of items, only the flinging. 

I can imagine there being some wrapper of `Lazy*` and Snapper which achieve this? This sounds very similar to what Accompanist Pager achieves, and that is heavily reliant on Snapper.

I'm going to mark this as closed and I don't this is in the realm of Snapper.

**Comment by hrach** [comment]
Thx for the input, I'll explore Pager a bit more.

**Comment by hrach** [comment]
> flingBehaviors have no control over the layout of items, only the flinging.

Now I see, that may be misunderstanding, I do not wanna have modify my layouting, the passed itemWidth was just stupid idea to let snapper know on what offsets those items are.

**Comment by chrisbanes** [comment]
Ah, sounds like you want `snapOffsetForItem`? https://chrisbanes.github.io/snapper/usage/#snap-positions

**Comment by hrach** [comment]
Well yeah, the API seems open enough, yet I opened this issue to avoid implementing SnapperLayoutInfo for a scrollable Row.

**Comment by trymnilsen** [comment]
@hrach Did you end up with anything here? I'm faced with the same situation and considered making a non-lazy `SnapperLayoutInfo` but If you have found a better way I'm all ears 👂

**Comment by chrisbanes** [comment]
There's no generic way to do this as `Row` or `Column` do not expose any layout info as state.

The `SnapperLayoutInfo` interface is there for this exact use case, but you'll need to implement the layout info above, together with the `ScrollState`.

**Comment by dazza5000** [comment]
I logged this Feature Request https://issuetracker.google.com/issues/228336552
