### ISSUE TITLE
Allow configuring the minimum velocity to scroll past an item

### ISSUE THREAD

**Issue by natanfudge** [chrisbanes/snapper#35]
The [documentation](https://chrisbanes.github.io/snapper/usage/#animation-specs) states: 
> decayAnimationSpec is the main spec used for flinging, and is used when the fling has enough velocity to scroll past the current item.

However, how do you actually _configure_ what is 'enough' velocity? I've noticed that the default velocity doesn't fit my needs very well. [Arpit Shukla](https://kotlinlang.slack.com/archives/CJLTWPH7S/p1638535378017500?thread_ts=1638461175.462100&cid=CJLTWPH7S) described this very well 10 months ago: 
> Sometimes I gently swipe to the left or right and expect that I will move to the next page, but that doesn't happen, the page moves a little and then comes back. Then I realize that I need to put more effort and swipe a little more :sweat_smile:.
I was thinking if it is possible to change that threshold velocity which is required to switch pages. I checked few other apps which provide a pager with a tab layout and there I can change pages with the slightest swipe.

> Attaching a video to give more context to the behavior I was referring to. 

https://user-images.githubusercontent.com/25990014/192085480-0d8cf1a2-4adb-4ad0-b04b-64f11eb8ee98.mp4

Perhaps it is configurable, but I cannot find how.

**Comment by chrisbanes** [comment]
It's not a configurable velocity value as such. We calculate the distance which the users velocity would provide, and then either use that if it reaches the 'next' page, or switch to a 'snap'.

What you're asking for can likely be implemented via the `snapIndex` parameter. Although we don't currently pass in the velocity.

**Comment by natanfudge** [comment]
I see, but it doesn't seem like I can get the behavior I want without taking the velocity into account. So would you consider passing in the velocity?
