### ISSUE TITLE
SnapOffsetForItem not working with relative fillParentMaxWidth

### ISSUE THREAD

**Issue by pablisco** [chrisbanes/snapper#6]
## Describe the bug
Using `fillParentMaxWith(fraction)` doesn't seem to be taken into account when calculating the offset:

This is the code:

```kotlin
    val lazyListState = rememberLazyListState()

    LazyRow(
        state = lazyListState,
        contentPadding = PaddingValues(dimensionResource(id = R.dimen.spacing_16)),
        horizontalArrangement = Arrangement.spacedBy(dimensionResource(id = R.dimen.spacing_16)),
        flingBehavior = rememberSnapperFlingBehavior(
            snapOffsetForItem = SnapOffsets.Center,
            lazyListState = lazyListState,
        )
    ) {
        items(items) { item ->
            Surface(
                modifier = Modifier
                    .fillParentMaxWidth(0.9f)
                    .height(150.dp)
                    .clip(Shapes.RoundedCorner.Regular),
                shape = Shapes.RoundedCorner.Regular,
                color = CuvvaTheme.color.surface,
            ) {
                // content redacted
            }
        }
    }
```

And this is how it looks:

<img width="500" src="https://user-images.githubusercontent.com/260697/144435681-b0872c7d-6541-4821-baa4-032f8c401b57.gif" />

The offset is not quite centered:

<img width="500" src="https://user-images.githubusercontent.com/260697/144434971-774ab1bf-43d8-4642-8801-15df0b1b08d2.png" />

## To Reproduce
See attached code on previous section to reproduce.

## Expected behavior
We were expecting the cards to be centered with a relative size of `0.9f`.

## Environment:
 - Android OS version: Android API 30
 - Device: Emulator
 - Library version: 0.1.0

**Comment by chrisbanes** [comment]
This is likely because you're not passing the content padding into `rememberSnapperFlingBehavior()`. See [here](https://chrisbanes.github.io/snapper/usage/#content-padding).

**Comment by pablisco** [comment]
OMG, you are so right :sweat\_smile:  works like a charm now. Classic case of "did not read the manual".  
 
<img height="80" src="https://user-images.githubusercontent.com/260697/144452440-ebe63825-ce6a-430d-80c6-e21676238d82.gif" />
  
![](https://c.tenor.com/_rrC613KIJMAAAAM/the-simpsons-homer-simpson.gif)

**Comment by ColtonIdle** [comment]
@pablisco can you share your code snippet by chance. Curious on what the final result ended up looking like.
