### ISSUE TITLE
Avoid printing `Napier` logs when `debugLog` is false

### ISSUE THREAD

**Issue by alexjlockwood** [chrisbanes/snapper#8]
I noticed that there are a few logs that are printed even when `debugLog` is set to `false` here https://github.com/chrisbanes/snapper/blob/35c0199c34e5bccb38825fbda48e6ecef01de672/lib/src/main/kotlin/dev/chrisbanes/snapper/SnapperFlingBehavior.kt#L44

**Comment by chrisbanes** [comment]
Woops. I'll fix this.
